apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: podinfo-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: istio-ingressgateway
  servers:
    - port:
        number: 8080
        name: http2
        protocol: HTTP2
      hosts:
        - "*.hus.nl"
