apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gatewayName }}
  namespace: "istio-system"
spec:
  gatewayClassName: istio
  listeners:
    - allowedRoutes:
        namespaces:
          from: All
      hostname: {{ printf  "*.%s" .Values.host | quote }}
      name: http
      port: 80
      protocol: HTTP