apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: podinfo-frontend
  namespace: {{ .Release.Namespace }}
spec:
  hostnames:
    - podinfo.{{ .Values.host }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.gatewayName }}
      namespace: istio-system
      port: 80
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: podinfo-frontend
          namespace: {{ .Release.Namespace }}
          port: 9898
          weight: 1